[FIX] - Add conditional on empty connected account
joelbutcher/socialstream pull request #136
Opened 2021-08-27 09:00 UTC by ejntaylor

I was getting the following exception when getting connected accounts for users which were seeded and did not have any connected accounts:

_Error Trying to get property 'user_id' of non-object_ 

I've included a conditional to check whether there is a connected account which fixes this for me.

2021-08-28 15:26 UTC, joelbutcher requested changes

2021-08-28 15:26 UTC, joelbutcher commented on src/HasConnectedAccounts.php
>          return $this->id == $connectedAccount->user_id;
Could remove the above and use`optional` here

2021-08-28 15:27 UTC, joelbutcher commented
So this could be solved either with `optional` as per my comment, or by properly type-hinting the property and have the developer responsible for ensuring the right type is passed.

Happy with either

2021-08-28 15:31 UTC, joelbutcher approved these changes

2021-08-28 15:31 UTC, merged

2021-08-30 08:58 UTC, ejntaylor commented
🙏 Thanks for the fix and merge!